"""budget schema

Revision ID: 7e678496fd60
Revises: 
Create Date: 2026-07-05 14:33:26.806797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e678496fd60'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('credit_card', 'checking', 'savings', 'investment', name='account_type'), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('current_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('apr', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('statement_close_day', sa.Integer(), nullable=True),
    sa.Column('due_day', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allocations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('pay_month', sa.Date(), nullable=False),
    sa.Column('fed_tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('state_tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sep_contribution', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('roth_contribution', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pay_month', name='uq_allocation_pay_month')
    )
    op.create_table('income_periods',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('work_month', sa.Date(), nullable=False),
    sa.Column('pay_month', sa.Date(), nullable=False),
    sa.Column('planned_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('actual_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_month', name='uq_income_period_work_month')
    )
    op.create_table('merchants',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('raw_aliases', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('default_category', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fixed_bills',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income_entries',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('period_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('type', sa.Enum('contract', 'interest', 'tbill', 'investment', 'other', name='income_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['period_id'], ['income_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promo_apr_windows',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('promo_end_date', sa.Date(), nullable=False),
    sa.Column('balance_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reward_rules',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('is_rotating', sa.Boolean(), nullable=False),
    sa.Column('promo_start_date', sa.Date(), nullable=True),
    sa.Column('promo_end_date', sa.Date(), nullable=True),
    sa.Column('spending_cap', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount_used', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('savings_goals',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixed_bill_payments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('bill_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('period_month', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['fixed_bills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('merchant', sa.String(length=200), nullable=False),
    sa.Column('merchant_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('tag', sa.Enum('fixed', 'variable', 'one_off', name='transaction_tag'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reward_rule_id', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['reward_rule_id'], ['reward_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('fixed_bill_payments')
    op.drop_table('savings_goals')
    op.drop_table('reward_rules')
    op.drop_table('promo_apr_windows')
    op.drop_table('income_entries')
    op.drop_table('fixed_bills')
    op.drop_table('merchants')
    op.drop_table('income_periods')
    op.drop_table('allocations')
    op.drop_table('accounts')
    # ### end Alembic commands ###
